import type { Mode, ParamsByMode } from "./modes";
import { createEffectStack, type EffectId, type FxParams } from "./fxParams";
import type { PaletteName } from "./paletteParams";

export type StudioPreset<M extends Mode = Mode> = {
  id: string;
  name: string;
  family: "Screen" | "Dither" | "Glitch" | "Custom";
  mode: M;
  palette?: PaletteName;
  params: Partial<ParamsByMode[M]>;
  fx?: Partial<FxParams>;
};

function stack(values: Partial<Record<EffectId, number>>, order: EffectId[] = ["acidGlow", "noise", "scanlines", "sharpen", "grain", "vignette"]): FxParams["stack"] {
  const enabled = Object.fromEntries(Object.entries(values).map(([key, value]) => [key, Number(value) !== 0])) as Partial<Record<EffectId, boolean>>;
  return createEffectStack(values, enabled, order);
}

export const STUDIO_PRESETS: StudioPreset[] = [
  {
    id: "acid-orange",
    name: "Acid Orange",
    family: "Dither",
    mode: "bayer",
    params: {
      matrix: "bayer4",
      scale: 3,
      levels: 5,
      contrast: 32,
      invert: false,
      postBlur: 0.12,
      colorMode: "rgb",
      palette: "acid_orange",
    },
    fx: {
      noise: 24,
      scanlines: 18,
      chromaticShift: 0,
      vignette: 28,
      posterize: 6,
      acidGlow: 72,
      sharpen: 18,
      grain: 12,
      seed: 6606,
      stack: stack({ acidGlow: 72, noise: 24, scanlines: 18, sharpen: 18, grain: 12, vignette: 28 }),
    },
  },
  {
    id: "game-boy-camera",
    name: "Game Boy Camera",
    family: "Dither",
    mode: "atkinson",
    params: {
      levels: 4,
      contrast: 18,
      brightness: 2,
      gamma: 0.95,
      serpentine: true,
      invert: false,
      colorMode: "source",
      palette: "gameboy",
    },
    fx: {
      noise: 10,
      scanlines: 8,
      sharpen: 22,
      grain: 8,
      vignette: 12,
      seed: 1989,
      stack: stack({ sharpen: 22, noise: 10, scanlines: 8, grain: 8, vignette: 12 }, ["sharpen", "noise", "scanlines", "grain", "vignette"]),
    },
  },
  {
    id: "macintosh-1bit",
    name: "Macintosh 1-Bit",
    family: "Dither",
    mode: "floyd_steinberg",
    params: {
      levels: 2,
      contrast: 24,
      brightness: 0,
      gamma: 1,
      serpentine: true,
      invert: false,
      colorMode: "mono",
      palette: "macintosh",
    },
    fx: {
      sharpen: 30,
      noise: 6,
      grain: 10,
      seed: 1984,
      stack: stack({ sharpen: 30, noise: 6, grain: 10 }, ["sharpen", "noise", "grain"]),
    },
  },
  {
    id: "pico8-dither",
    name: "PICO-8 Dither",
    family: "Dither",
    mode: "bayer",
    params: {
      matrix: "bayer4",
      scale: 4,
      levels: 5,
      contrast: 18,
      invert: false,
      colorMode: "rgb",
      palette: "pico8",
      postBlur: 0,
    },
    fx: {
      posterize: 7,
      sharpen: 18,
      noise: 8,
      seed: 8008,
      stack: stack({ posterize: 7, sharpen: 18, noise: 8 }, ["posterize", "sharpen", "noise"]),
    },
  },
  {
    id: "cga-signal",
    name: "CGA Signal",
    family: "Screen",
    mode: "bayer",
    params: {
      matrix: "lines",
      scale: 3,
      levels: 4,
      contrast: 26,
      invert: false,
      colorMode: "rgb",
      palette: "cga",
      postBlur: 0.02,
    },
    fx: {
      chromaticShift: 6,
      scanlines: 34,
      sharpen: 20,
      vignette: 20,
      seed: 5150,
      stack: stack({ chromaticShift: 6, scanlines: 34, sharpen: 20, vignette: 20 }, ["chromaticShift", "scanlines", "sharpen", "vignette"]),
    },
  },
  {
    id: "ascii-terminal",
    name: "ASCII Terminal",
    family: "Glitch",
    mode: "bayer",
    params: {
      matrix: "bayer8",
      scale: 2,
      levels: 5,
      contrast: 22,
      invert: false,
      colorMode: "rgb",
      palette: "acid_orange",
      postBlur: 0,
    },
    fx: {
      ascii: 72,
      acidGlow: 34,
      scanlines: 12,
      noise: 16,
      sharpen: 22,
      seed: 1337,
      stack: stack({ ascii: 72, acidGlow: 34, scanlines: 12, noise: 16, sharpen: 22 }, ["ascii", "acidGlow", "scanlines", "noise", "sharpen"]),
    },
  },
  {
    id: "inferno-print",
    name: "Inferno Print",
    family: "Dither",
    mode: "bayer",
    params: {
      matrix: "bayer8",
      scale: 2,
      levels: 6,
      contrast: 42,
      invert: false,
      postBlur: 0,
      colorMode: "rgb",
      palette: "acid_orange",
    },
    fx: {
      acidGlow: 86,
      noise: 34,
      scanlines: 0,
      posterize: 4,
      sharpen: 34,
      grain: 26,
      vignette: 36,
      seed: 9006,
      stack: stack({ acidGlow: 86, sharpen: 34, noise: 34, grain: 26, vignette: 36 }, ["acidGlow", "sharpen", "noise", "grain", "vignette"]),
    },
  },
  {
    id: "soft-solar",
    name: "Soft Solar",
    family: "Screen",
    mode: "floyd_steinberg",
    params: {
      levels: 5,
      contrast: -8,
      brightness: 10,
      gamma: 0.88,
      serpentine: true,
      invert: false,
      colorMode: "source",
      palette: "warm_print",
    },
    fx: {
      acidGlow: 34,
      noise: 12,
      grain: 34,
      vignette: 8,
      posterize: 6,
      seed: 2022,
      stack: stack({ grain: 34, acidGlow: 34, noise: 12, vignette: 8, posterize: 6 }, ["grain", "acidGlow", "noise", "vignette", "posterize"]),
    },
  },
  {
    id: "xerox-heat",
    name: "Xerox Heat",
    family: "Dither",
    mode: "halftone",
    palette: "xerox_heat",
    params: {
      cellSize: 10,
      dotSize: 116,
      minDot: 2,
      gamma: 1.12,
      contrast: 38,
      shape: "circle",
      roundness: 100,
      jitter: 16,
      stretch: 100,
      invert: false,
      colorMode: "source",
      palette: "xerox_heat",
    },
    fx: {
      noise: 32,
      acidGlow: 58,
      sharpen: 42,
      grain: 26,
      vignette: 30,
      posterize: 4,
      seed: 2606,
      stack: stack({ posterize: 4, acidGlow: 58, sharpen: 42, noise: 32, grain: 26, vignette: 30 }, ["posterize", "acidGlow", "sharpen", "noise", "grain", "vignette"]),
    },
  },
  {
    id: "red-signal",
    name: "Red Signal",
    family: "Glitch",
    mode: "bayer",
    params: {
      matrix: "lines",
      scale: 3,
      levels: 4,
      contrast: 36,
      invert: false,
      colorMode: "rgb",
      palette: "acid_orange",
      postBlur: 0.04,
    },
    fx: {
      acidGlow: 78,
      chromaticShift: 8,
      scanlines: 36,
      noise: 20,
      sharpen: 30,
      vignette: 46,
      seed: 606,
      stack: stack({ acidGlow: 78, chromaticShift: 8, scanlines: 36, sharpen: 30, noise: 20, vignette: 46 }, ["acidGlow", "chromaticShift", "scanlines", "sharpen", "noise", "vignette"]),
    },
  },
  {
    id: "poster-decay",
    name: "Poster Decay",
    family: "Dither",
    mode: "atkinson",
    params: {
      levels: 3,
      contrast: 34,
      brightness: -4,
      gamma: 1.18,
      serpentine: true,
      invert: false,
      colorMode: "source",
      palette: "acid_orange",
    },
    fx: {
      acidGlow: 46,
      noise: 38,
      grain: 42,
      sharpen: 24,
      scanlines: 12,
      vignette: 34,
      seed: 404,
      stack: stack({ acidGlow: 46, sharpen: 24, noise: 38, grain: 42, scanlines: 12, vignette: 34 }, ["acidGlow", "sharpen", "noise", "grain", "scanlines", "vignette"]),
    },
  },
];
